version: '2'
services:
    mystudent-app:
        image: jreyesromero/mystudent
        external_links:
            - mystudent-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mystudent?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mystudent-mysql:
        extends:
            file: mysql.yml
            service: mystudent-mysql
